# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd868dd09a4cf3dbd725963ebeceda2e65ba7d385251598380950ffd10d992a705376fa7de8f889f8e370813d9bbd8e387c1c8904efc4b9111eb444083b40828

test:
  secret_key_base: 486aa7c257af57c399ab3da15f4686174d1d2433c01c362fca5ee1b0c8fc1a70c0d5c26b78626880211a12c011c8d48ee4b2a210bc6e984fd46b762adf07583e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
